### ISSUE TITLE
Unable to  switch connection with "withConnection" 

### ISSUE THREAD

**Issue by dshrestha** [grails/gorm-mongodb#39]
I am trying to switch between different connection using "withConnection" as mentioned here:http://gorm.grails.org/6.0.x/whatsNew/manual/ but I end up getting following error

> No signature of method: mgmigration.ChangeSet.withConnection() is applicable for argument types: (java.lang.String, mgmigration.MigrateService$__tt__executeChangeSet_closure2) values:

I do have "org.grails.plugins:hibernate5" dependency commented out so I am not using hibernate and in my domain object I have specified both connections properly.

```
package mgmigration

import org.bson.types.ObjectId

class ChangeSet {

    ObjectId id
    String author
    String comment
    String migrationClassName
    String revision
    Date dateCreated
    Date lastUpdated

    static mapping = {
        mapWith "mongo"
        connections analytics, reporting
        collection "migrationChangeSet"
        id attr: "_id"
        autoTimestamp true
        version false
    }
}
```
And my application.yml has connections params properly defined too.

```
   mongodb:
      connections:
        analytics:
          url: 'mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_REPLICA_SET}/${MONGODB_ANALYTICS_DATABASE}?${MONGODB_CONNECTION_OPTIONS}'
        reporting:
          url: 'mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_REPLICA_SET}/${MONGODB_REPORTING_DATABASE}?${MONGODB_CONNECTION_OPTIONS}'
```

I am using mongodb plugin 'org.grails.plugins:mongodb:6.0.7' and grails 3.2.6
